### ISSUE TITLE
Не работает хот лоадер

### ISSUE THREAD

**Issue by nimblemo** [LeeSwagger/webpack-starter#1]
Здравствуйте, скачал проект, установил, а хот лоадер не работает. Среда разработки visual studio code

**Comment by LeeSwagger** [comment]
Добрый день! А в чем именно выражается проблема? Стили не обновляются без перезагрузки страницы?

**Comment by nimblemo** [comment]
Нет вообще страница не обновляется при изменении содержимого проекта.

**Comment by LeeSwagger** [comment]
Т.е. запустили проект командой npm start, зашли на localhost:9000, и не обновляются ни css, ни js?
